[package]
name = "paperz"
version = "0.1.0"
authors = ["Michael Hueschen <m@mhueschen.space>"]
edition = "2018"
license = "MIT"

[dependencies]
hdk = "0.0.131"
serde = "1"

common = { git = "https://github.com/neighbour-hoods/social_sensemaker.git", rev = "7791407d57b8faf97b88fc5fef1249fdbe5797fb" }
rep_lang_core = { git = "https://github.com/neighbour-hoods/rep_lang.git", rev = "3cadc2eebe7c315844527de4bab7398108a17b57", features = ["hc"] }
rep_lang_runtime = { git = "https://github.com/neighbour-hoods/rep_lang.git", rev = "3cadc2eebe7c315844527de4bab7398108a17b57", features = ["hc"] }
hub = { path = "../hub" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
